name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches: [master]

jobs:
  # =====================================
  # 1) Testes UnitÃ¡rios
  # =====================================
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: pytest -q


  # =====================================
  # 2) Build + Push Docker + Deploy
  # =====================================        
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Load secrets
      - name: Set env vars
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "RENDER_DEPLOY_HOOK=${{ secrets.RENDER_DEPLOY_HOOK }}" >> $GITHUB_ENV

      - name: Log in to DockerHub
        if: ${{ env.DOCKERHUB_USERNAME != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t rossmann-prophet:latest .

      - name: Tag & push to DockerHub
        if: ${{ env.DOCKERHUB_USERNAME != '' }}
        run: |
          docker tag rossmann-prophet:latest ${{ secrets.DOCKERHUB_USERNAME }}/rossmann-prophet:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rossmann-prophet:latest

      - name: Deploy to Render
        if: github.ref == 'refs/heads/master' && env.RENDER_DEPLOY_HOOK != ''
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
